// Lista predefinida de palabras prohibidas (insultos, spam, etc.)
const DEFAULT_BANNED_WORDS = [
    'idiota',
    'imbécil',
    'estúpido',
    'bruto',
    'tonto',
    'pendejo',
    'maldito',
    'desgraciado',
    'basura',
    'naco',
    'ridículo',
    'fracasado',
    'payaso',
    'retrasado',
    'asqueroso',
    'repugnante',
    'despreciable',
    'patético',
    'vergüenza',
    'viagra',
    'cialis',
    'casino',
    'crypto',
    'bitcoin',
    'ganar dinero',
    'click aqui',
    'enlace',
    'link afiliado',
    '18+',
    'xxx',
    'porno',
    'sexo',
    'droga',
    'cocaína',
    'marihuana',
    'heroína',
    'fentanilo'
];

module.exports = DEFAULT_BANNED_WORDS;
